### ISSUE TITLE
Move to EventBridge notifications

### ISSUE THREAD

**Issue by mmehrten** [aws-samples/aws-health-aware#66]
AHA currently uses AWS Health API polling to get event notifications. Instead, AHA could use [EventBridge notifications](https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html) to respond to AWS Health events. This would be more efficient than polling every minute.

**Comment by Saff-Buraq-Dev** [comment]
A push based mechanism is certainly always easier than a pull based one. Correct me if I'm wrong but it seems that it won't work if the Organizations View feature is enabled, because eventbridge will capture the account event and not all the aggregated events for all the accounts. So the actual solution is generic and works in both cases.

**Comment by Saff-Buraq-Dev** [comment]
> AHA currently uses AWS Health API polling to get event notifications. Instead, AHA could use [EventBridge notifications](https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html) to respond to AWS Health events. This would be more efficient than polling every minute.

A push based mechanism is certainly always easier than a pull based one. Correct me if I'm wrong but it seems that it won't work if the Organizations View feature is enabled, because eventbridge will capture the account event and not all the aggregated events for all the accounts. So the actual solution is generic and works in both cases.

**Comment by mmehrten** [comment]
That's true @Saff-Buraq-Dev , but EventBridge would be preferred for non-organization view use cases.

**Comment by jack-parsons-bjss** [comment]
I think the current mechanism is preferred because EventBridge events are best effort rather than guaranteed delivery? Happy to be corrected.
